export interface Video {
  id: string;
  title: string;
  thumbnail: string;
  description: string;
  views: number;
  uploader: string;
  uploadDate: string;
  likes: number;
}

export const videos: Video[] = [
  {
    id: "1",
    title: "Sample Video 1",
    thumbnail: "https://i.postimg.cc/mZKp6Nbz/video-1.jpg",
    description: "Description for video 1",
    views: 100,
    uploader: "Uploader 1",
    uploadDate: "2023-01-01",
    likes: 10,
  },
  {
    id: "2",
    title: "Sample Video 2",
    thumbnail: "https://i.postimg.cc/FFgwJSsS/ol-Ra6n-XPv-Qy-G5w4-T-generated-image.jpg",
    description: "Description for video 2",
    views: 500,
    uploader: "PREETAM SINGH",
    uploadDate: "1 day ago",
    likes: 10,
  },
  {
    id: "3",
    title: "Sample Video 3",
    thumbnail: "https://i.postimg.cc/SxtBxpQt/06-image.jpg",
    description: "Description for video 3",
    views: 300,
    uploader: "PREETAM SINGH",
    uploadDate: "2 days ago",
    likes: 15,
  },
  {
    id: "4",
    title: "Sample Video 4",
    thumbnail: "https://i.postimg.cc/vTMjNYXD/ilh-kljikj-kj-gv-07-Flowcharts-Q1.jpg",
    description: "Description for video 4",
    views: 200,
    uploader: "PREETAM SINGH",
    uploadDate: "3 days ago",
    likes: 20,
  },
  {
    id: "5",
    title: "Sample Video 5",
    thumbnail: "https://i.postimg.cc/25sgnFZQ/08-Flowcharts-Q2.jpg",
    description: "Description for video 5",
    views: 400,
    uploader: "PREETAM SINGH",
    uploadDate: "4 days ago",
    likes: 25,
  },
  {
    id: "6",
    title: "Sample Video 6",
    thumbnail: "https://i.postimg.cc/W4FQDfhp/09-Flowcharts-Q3.jpg",
    description: "Description for video 6",
    views: 350,
    uploader: "Preetam Singh",
    uploadDate: "5 days ago",
    likes: 18,
  },
  {
    id: "7",
    title: "Sample Video 7",
    thumbnail: "https://i.postimg.cc/rm53j01v/10.jpg",
    description: "Description for video 7",
    views: 450,
    uploader: "Preetam Singh",
    uploadDate: "6 days ago",
    likes: 22,
  },
  {
    id: "8",
    title: "Sample Video 8",
    thumbnail: "https://i.postimg.cc/j2X9Vpkc/Flowcharts-Q5.jpg",
    description: "Description for video 8",
    views: 500,
    uploader: "Preetam Singh",
    uploadDate: "7 days ago",
    likes: 30,
  },
  {
    id: "9",
    title: "Sample Video 9",
    thumbnail: "https://i.postimg.cc/QC4bJhy2/Kp31ha3-Nfr4-LYQni-generated-image-1.jpg",
    description: "Description for video 9",
    views: 600,
    uploader: "Preetam Singh",
    uploadDate: "8 days ago",
    likes: 35,
  },
  {
    id: "10",
    title: "Sample Video 10",
    thumbnail: "https://i.postimg.cc/YqPR42gg/t-N8-CRb5om-ZPKspi-J-generated-image-1.jpg",
    description: "Description for video 10",
    views: 550,
    uploader: "Preetam Singh",
    uploadDate: "9 days ago",
    likes: 28,
  },
  {
    id: "11",
    title: "Sample Video 11",
    thumbnail: "https://i.postimg.cc/5tVwvXtH/image.png",
    description: "Description for video 11",
    views: 700,
    uploader: "Preetam Singh",
    uploadDate: "10 days ago",
    likes: 40,
  },
  {
    id: "12",
    title: "Sample Video 12",
    thumbnail: "https://i.postimg.cc/wjKJ81LW/image.png",
    description: "Description for video 12",
    views: 480,
    uploader: "Preetam Singh",
    uploadDate: "11 days ago",
    likes: 32,
  },
  {
    id: "13",
    title: "Sample Video 13",
    thumbnail: "https://i.postimg.cc/0NHPFHB7/image.png",
    description: "Description for video 13",
    views: 520,
    uploader: "Preetam Singh",
    uploadDate: "12 days ago",
    likes: 27,
  },
  {
    id: "14",
    title: "Sample Video 14",
    thumbnail: "https://i.postimg.cc/5ySyFSsy/image.png",
    description: "Description for video 14",
    views: 600,
    uploader: "Preetam Singh",
    uploadDate: "13 days ago",
    likes: 45,
  },
  {
    id: "15",
    title: "Sample Video 15",
    thumbnail: "https://i.postimg.cc/wTBgVzv0/image.png",
    description: "Description for video 15",
    views: 550,
    uploader: "Preetam Singh",
    uploadDate: "14 days ago",
    likes: 38,
  },
  {
    id: "16",
    title: "Sample Video 16",
    thumbnail: "https://i.postimg.cc/15b2q1Ng/image.png",
    description: "Description for video 16",
    views: 470,
    uploader: "Preetam Singh",
    uploadDate: "15 days ago",
    likes: 33,
  },
  {
    id: "17",
    title: "Sample Video 17",
    thumbnail: "https://i.postimg.cc/qRmZBPTv/image.png",
    description: "Description for video 17",
    views: 490,
    uploader: "Preetam Singh",
    uploadDate: "16 days ago",
    likes: 29,
  },
  {
    id: "18",
    title: "Sample Video 18",
    thumbnail: "https://i.postimg.cc/5t8SkZ0R/image.png",
    description: "Description for video 18",
    views: 510,
    uploader: "Preetam Singh",
    uploadDate: "17 days ago",
    likes: 36,
  },
  {
    id: "19",
    title: "Sample Video 19",
    thumbnail: "https://i.postimg.cc/3xkZTkLV/image.png",
    description: "Description for video 19",
    views: 530,
    uploader: "Preetam Singh",
    uploadDate: "18 days ago",
    likes: 41,
  },
  {
    id: "20",
    title: "Sample Video 20",
    thumbnail: "https://i.postimg.cc/c488dPy1/image.png",
    description: "Description for video 20",
    views: 570,
    uploader: "Preetam Singh",
    uploadDate: "19 days ago",
    likes: 44,
  },
  {
    id: "21",
    title: "Sample Video 21",
    thumbnail: "https://i.postimg.cc/RhxQmmst/image.png",
    description: "Description for video 21",
    views: 620,
    uploader: "Preetam Singh",
    uploadDate: "20 days ago",
    likes: 50,
  },
  {
    id: "22",
    title: "Sample Video 22",
    thumbnail: "https://i.postimg.cc/fTwqS7C9/image.png",
    description: "Description for video 22",
    views: 630,
    uploader: "Preetam Singh",
    uploadDate: "21 days ago",
    likes: 52,
  },
  {
    id: "23",
    title: "Sample Video 23",
    thumbnail: "https://i.postimg.cc/RCfQC3zn/image.png",
    description: "Description for video 23",
    views: 640,
    uploader: "Preetam Singh",
    uploadDate: "22 days ago",
    likes: 55,
  },
  {
    id: "24",
    title: "Sample Video 24",
    thumbnail: "https://i.postimg.cc/9FLvbgN2/image.png",
    description: "Description for video 24",
    views: 650,
    uploader: "Preetam Singh",
    uploadDate: "23 days ago",
    likes: 58,
  },
  {
    id: "25",
    title: "Sample Video 25",
    thumbnail: "https://i.postimg.cc/BQkHDHfg/image.png",
    description: "Description for video 25",
    views: 660,
    uploader: "Preetam Singh",
    uploadDate: "24 days ago",
    likes: 60,
  },
  {
    id: "26",
    title: "Sample Video 26",
    thumbnail: "https://i.postimg.cc/qvY9Km17/image.png",
    description: "Description for video 26",
    views: 670,
    uploader: "Preetam Singh",
    uploadDate: "25 days ago",
    likes: 62,
  },
  {
    id: "27",
    title: "Sample Video 27",
    thumbnail: "https://i.postimg.cc/BQX6GnwP/image.png",
    description: "Description for video 27",
    views: 680,
    uploader: "Preetam Singh",
    uploadDate: "26 days ago",
    likes: 65,
  },
  {
    id: "28",
    title: "Sample Video 28",
    thumbnail: "https://i.postimg.cc/G36smfTp/image.png",
    description: "Description for video 28",
    views: 700,
    uploader: "Preetam Singh",
    uploadDate: "27 days ago",
    likes: 70,
  },
  {
    id: "29",
    title: "Sample Video 29",
    thumbnail: "https://i.postimg.cc/YCzkHZgZ/image.png",
    description: "Description for video 29",
    views: 710,
    uploader: "Preetam Singh",
    uploadDate: "28 days ago",
    likes: 72,
  },
  {
    id: "30",
    title: "Sample Video 30",
    thumbnail: "https://i.postimg.cc/QdXbQqc1/image.png",
    description: "Description for video 30",
    views: 730,
    uploader: "Preetam Singh",
    uploadDate: "29 days ago",
    likes: 75,
  },
  {
    id: "31",
    title: "Sample Video 31",
    thumbnail: "https://i.postimg.cc/nhBJmpYC/image.png",
    description: "Description for video 31",
    views: 740,
    uploader: "Preetam Singh",
    uploadDate: "30 days ago",
    likes: 78,
  },
  {
    id: "32",
    title: "Sample Video 32",
    thumbnail: "https://i.postimg.cc/KYTwVNsj/image.png",
    description: "Description for video 32",
    views: 750,
    uploader: "Preetam Singh",
    uploadDate: "31 days ago",
    likes: 80,
  },
  {
    id: "33",
    title: "Sample Video 33",
    thumbnail: "https://i.postimg.cc/rsT9mGJh/image.png",
    description: "Description for video 33",
    views: 760,
    uploader: "Preetam Singh",
    uploadDate: "32 days ago",
    likes: 85,
  },
  {
    id: "34",
    title: "Sample Video 34",
    thumbnail: "https://i.postimg.cc/L5Mwk1H7/image.png",
    description: "Description for video 34",
    views: 770,
    uploader: "Preetam Singh",
    uploadDate: "33 days ago",
    likes: 88,
  },
  {
    id: "35",
    title: "Sample Video 35",
    thumbnail: "https://i.postimg.cc/L5Mwk1H7/image.png",
    description: "Description for video 35",
    views: 780,
    uploader: "Preetam Singh",
    uploadDate: "34 days ago",
    likes: 90,
  },
  {
    id: "36",
    title: "Sample Video 36",
    thumbnail: "https://i.postimg.cc/L5Mwk1H7/image.png",
    description: "Description for video 36",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "35 days ago",
    likes: 92,
  },
  {
    id: "37",
    title: "Sample Video 37",
    thumbnail: "https://i.postimg.cc/Wpw2qjV9/image.png",
    description: "Description for video 37",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "36 days ago",
    likes: 95,
  },
  {
    id: "38",
    title: "Sample Video 38",
    thumbnail: "https://i.postimg.cc/Wpw2qjV9/image.png",
    description: "Description for video 38",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "37 days ago",
    likes: 98,
  },
  {
    id: "39",
    title: "Sample Video 39",
    thumbnail: "https://i.postimg.cc/c488dPy1/image.png",
    description: "Description for video 39",
    views: 570,
    uploader: "Preetam Singh",
    uploadDate: "19 days ago",
    likes: 44,
  },
  {
    id: "40",
    title: "Sample Video 40",
    thumbnail: "https://i.postimg.cc/RhxQmmst/image.png",
    description: "Description for video 40",
    views: 590,
    uploader: "Preetam Singh",
    uploadDate: "20 days ago",
    likes: 47,
  },
  {
    id: "41",
    title: "Sample Video 41",
    thumbnail: "https://i.postimg.cc/RhxQmmst/image.png",
    description: "Description for video 41",
    views: 620,
    uploader: "Preetam Singh",
    uploadDate: "21 days ago",
    likes: 50,
  },
  {
    id: "42",
    title: "Sample Video 42",
    thumbnail: "https://i.postimg.cc/fTwqS7C9/image.png",
    description: "Description for video 42",
    views: 630,
    uploader: "Preetam Singh",
    uploadDate: "22 days ago",
    likes: 52,
  },
  {
    id: "43",
    title: "Sample Video 43",
    thumbnail: "https://i.postimg.cc/RCfQC3zn/image.png",
    description: "Description for video 43",
    views: 640,
    uploader: "Preetam Singh",
    uploadDate: "23 days ago",
    likes: 55,
  },
  {
    id: "44",
    title: "Sample Video 44",
    thumbnail: "https://i.postimg.cc/9FLvbgN2/image.png",
    description: "Description for video 44",
    views: 650,
    uploader: "Preetam Singh",
    uploadDate: "24 days ago",
    likes: 58,
  },
  {
    id: "45",
    title: "Sample Video 45",
    thumbnail: "https://i.postimg.cc/BQkHDHfg/image.png",
    description: "Description for video 45",
    views: 660,
    uploader: "Preetam Singh",
    uploadDate: "25 days ago",
    likes: 60,
  },
  {
    id: "46",
    title: "Sample Video 46",
    thumbnail: "https://i.postimg.cc/qvY9Km17/image.png",
    description: "Description for video 46",
    views: 670,
    uploader: "Preetam Singh",
    uploadDate: "26 days ago",
    likes: 62,
  },
  {
    id: "47",
    title: "Sample Video 47",
    thumbnail: "https://i.postimg.cc/BQX6GnwP/image.png",
    description: "Description for video 47",
    views: 680,
    uploader: "Preetam Singh",
    uploadDate: "27 days ago",
    likes: 65,
  },
  {
    id: "48",
    title: "Sample Video 48",
    thumbnail: "https://i.postimg.cc/G36smfTp/image.png",
    description: "Description for video 48",
    views: 700,
    uploader: "Preetam Singh",
    uploadDate: "28 days ago",
    likes: 70,
  },
  {
    id: "49",
    title: "Sample Video 49",
    thumbnail: "https://i.postimg.cc/YCzkHZgZ/image.png",
    description: "Description for video 49",
    views: 710,
    uploader: "Preetam Singh",
    uploadDate: "29 days ago",
    likes: 72,
  },
  {
    id: "50",
    title: "Sample Video 50",
    thumbnail: "https://i.postimg.cc/QdXbQqc1/image.png",
    description: "Description for video 50",
    views: 730,
    uploader: "Preetam Singh",
    uploadDate: "30 days ago",
    likes: 75,
  },
  {
    id: "51",
    title: "Sample Video 51",
    thumbnail: "https://i.postimg.cc/nhBJmpYC/image.png",
    description: "Description for video 51",
    views: 740,
    uploader: "Preetam Singh",
    uploadDate: "31 days ago",
    likes: 78,
  },
  {
    id: "52",
    title: "Sample Video 52",
    thumbnail: "https://i.postimg.cc/KYTwVNsj/image.png",
    description: "Description for video 52",
    views: 750,
    uploader: "Preetam Singh",
    uploadDate: "32 days ago",
    likes: 80,
  },
  {
    id: "53",
    title: "Sample Video 53",
    thumbnail: "https://i.postimg.cc/rsT9mGJh/image.png",
    description: "Description for video 53",
    views: 760,
    uploader: "Preetam Singh",
    uploadDate: "33 days ago",
    likes: 85,
  },
  {
    id: "54",
    title: "Sample Video 54",
    thumbnail: "https://i.postimg.cc/L5Mwk1H7/image.png",
    description: "Description for video 54",
    views: 770,
    uploader: "Preetam Singh",
    uploadDate: "34 days ago",
    likes: 88,
  },
  {
    id: "55",
    title: "Sample Video 55",
    thumbnail: "https://i.postimg.cc/L5Mwk1H7/image.png",
    description: "Description for video 55",
    views: 780,
    uploader: "Preetam Singh",
    uploadDate: "35 days ago",
    likes: 90,
  },
  {
    id: "56",
    title: "Sample Video 56",
    thumbnail: "https://i.postimg.cc/Wpw2qjV9/image.png",
    description: "Description for video 56",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "36 days ago",
    likes: 92,
  },
  {
    id: "57",
    title: "Sample Video 57",
    thumbnail: "https://i.postimg.cc/Wpw2qjV9/image.png",
    description: "Description for video 57",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "37 days ago",
    likes: 95,
  },
  {
    id: "58",
    title: "Sample Video 58",
    thumbnail: "https://i.postimg.cc/c488dPy1/image.png",
    description: "Description for video 58",
    views: 790,
    uploader: "Preetam Singh",
    uploadDate: "38 days ago",
    likes: 98,
  },
  {
    id: "59",
    title: "Sample Video 59",
    thumbnail: "https://i.postimg.cc/RhxQmmst/image.png",
    description: "Description for video 59",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "39 days ago",
    likes: 100,
  },
  {
    id: "60",
    title: "Sample Video 60",
    thumbnail: "https://i.postimg.cc/fTXm4VQH/image.png",
    description: "Description for video 60",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "61",
    title: "Sample Video 61",
    thumbnail: "https://i.postimg.cc/MT2JF373/image.png",
    description: "Description for video 61",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "62",
    title: "Sample Video 62",
    thumbnail: "https://i.postimg.cc/bJmfLxTs/image.png",
    description: "Description for video 62",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "63",
    title: "Sample Video 63",
    thumbnail: "https://i.postimg.cc/43yYxqtL/Eux-Hhs-Dw-HFTzxf-DC-generated-image.jpg",
    description: "Description for video 63",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "64",
    title: "Sample Video 64",
    thumbnail: "https://i.postimg.cc/QMjLNRy2/wiiiqj-Op0-YUJrz-Hv-generated-image.jpg",
    description: "Description for video 64",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "65",
    title: "Sample Video 65",
    thumbnail: "https://i.postimg.cc/J7cs1dQj/nm-Oad-Nn-Fa7h-VTt-Xd-generated-image.jpg",
    description: "Description for video 65",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "66",
    title: "Sample Video 66",
    thumbnail: "https://i.postimg.cc/bwFS2Cdd/l-DQb-ZEvo-O0-Utsc-Ad-generated-image.jpg",
    description: "Description for video 66",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "67",
    title: "Sample Video 67",
    thumbnail: "https://i.postimg.cc/ZnfFKXsH/E7u-Gkr-Kh-VZn-K6-JMG-generated-image.jpg",
    description: "Description for video 67",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "68",
    title: "Sample Video 68",
    thumbnail: "https://i.postimg.cc/3Rm5D5sK/GSqdq-D5a6-B8-T0uta-generated-image.jpg",
    description: "Description for video 68",
    views: 810,
    uploader: "Preetam Singh",
    uploadDate: "40 days ago",
    likes: 98,
  },
  {
    id: "69",
    title: "Sample Video 69",
    thumbnail: "https://i.postimg.cc/nczqJyq3/gz-CFcd9-Hhtrdxre-T-generated-image-1.jpg",
    description: "Description for video 69",
    views: 500,
    uploader: "Preetam SINGH",
    uploadDate: "30 days ago",
    likes: 50,
  },
  {
    id: "70",
    title: "Sample Video 70",
    thumbnail: "https://i.postimg.cc/9MC2v3cg/PDwno-W1wvx-O9-Tw-Zr-generated-image.jpg",
    description: "Description for video 70",
    views: 600,
    uploader: "Unknown",
    uploadDate: "25 days ago",
    likes: 60,
  },
  {
    id: "71",
    title: "Sample Video 71",
    thumbnail: "https://i.postimg.cc/52YyPn1K/VWspsl9t5xz-NJr-SD-generated-image.jpg",
    description: "Description for video 71",
    views: 700,
    uploader: "Unknown",
    uploadDate: "20 days ago",
    likes: 70,
  },
  {
    id: "72",
    title: "Sample Video 72",
    thumbnail: "https://i.postimg.cc/qq6vvxwZ/ZAt5of-J4-Zi0-WFX53-generated-image.jpg",
    description: "Description for video 72",
    views: 800,
    uploader: "Unknown",
    uploadDate: "15 days ago",
    likes: 80,
  },
  {
    id: "73",
    title: "Sample Video 73",
    thumbnail: "https://i.postimg.cc/fLJ9YX5Y/GMly51-Kh-SPqt-Qf-Ul-generated-image.jpg",
    description: "Description for video 73",
    views: 900,
    uploader: "Unknown",
    uploadDate: "10 days ago",
    likes: 90,
  },
  {
    id: "74",
    title: "Sample Video 74",
    thumbnail: "https://i.postimg.cc/1zgmHHhR/K4n-H4-MLPo-TXlz-RCO-generated-image-1.jpg",
    description: "Description for video 74",
    views: 1000,
    uploader: "Unknown",
    uploadDate: "5 days ago",
    likes: 100,
  },
  {
    id: "75",
    title: "Sample Video 75",
    thumbnail: "https://i.postimg.cc/FzGXmd5n/k-ZRSHm-XYYDfz-Gss-Y-generated-image.jpg",
    description: "Description for video 75",
    views: 1100,
    uploader: "Unknown",
    uploadDate: "2 days ago",
    likes: 110,
  },
  {
    id: "76",
    title: "Sample Video 76",
    thumbnail: "https://i.postimg.cc/J03Zh8PF/u-Qc-QEMBsbvfi-Px-Af-generated-image.jpg",
    description: "Description for video 76",
    views: 1200,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 120,
  },
  {
    id: "77",
    title: "Sample Video 77",
    thumbnail: "https://i.postimg.cc/xTtNpt7L/ZI0-Cp-WQ9-Og-Sc-Gg-Br-generated-image.jpg",
    description: "Description for video 77",
    views: 1300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 130,
  },
  {
    id: "78",
    title: "Sample Video 78",
    thumbnail: "https://i.postimg.cc/hj1tzGRV/Ga-OYTBBU22gcbk-KL-generated-image.jpg",
    description: "Description for video 78",
    views: 1400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 140,
  },
  {
    id: "79",
    title: "Sample Video 79",
    thumbnail: "https://i.postimg.cc/pLjx5dDy/Ug-BMIIw-Ob-FEG5-Bl9-generated-image-1.jpg",
    description: "Description for video 79",
    views: 1500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 150,
  },
  {
    id: "80",
    title: "Sample Video 80",
    thumbnail: "https://i.postimg.cc/3J4Qzwf9/TDyg7e0-Ga23-C64-EU-generated-image.jpg",
    description: "Description for video 80",
    views: 1600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 160,
  },
  {
    id: "81",
    title: "Sample Video 81",
    thumbnail: "https://i.postimg.cc/kX3d3Crm/4n9jpa692h55-Uy-UY-generated-image.jpg",
    description: "Description for video 81",
    views: 1700,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 170,
  },
  {
    id: "82",
    title: "Sample Video 82",
    thumbnail: "https://i.postimg.cc/T1nFYy8X/n7-ORMb-W1g-F36-Y4-FH-generated-image.jpg",
    description: "Description for video 82",
    views: 1800,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 180,
  },
  {
    id: "83",
    title: "Sample Video 83",
    thumbnail: "https://i.postimg.cc/hGhYQZFs/69-Q3-V1r-Nr-QSBAli-N-generated-image.jpg",
    description: "Description for video 83",
    views: 1900,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 190,
  },
  {
    id: "84",
    title: "Sample Video 84",
    thumbnail: "https://i.postimg.cc/yYMxbtjg/ea-T6wx0id-PIWr-QMQ-generated-image.jpg",
    description: "Description for video 84",
    views: 2000,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 200,
  },
  {
    id: "85",
    title: "Sample Video 85",
    thumbnail: "https://i.postimg.cc/1zHz4tQw/d-Wl-Ec-TCUAJGc-Aq-Nk-generated-image.jpg",
    description: "Description for video 85",
    views: 2100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 210,
  },
  {
    id: "86",
    title: "Sample Video 86",
    thumbnail: "https://i.postimg.cc/pd2WNHFT/8-Mzvtl-Xhzgfx-YG0-U-generated-image.jpg",
    description: "Description for video 86",
    views: 2200,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 220,
  },
  {
    id: "87",
    title: "Sample Video 87",
    thumbnail: "https://i.postimg.cc/YCJbsrLc/IOMB6ff0-Tr-Mx69-Ky-generated-image.jpg",
    description: "Description for video 87",
    views: 2300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 230,
  },
  {
    id: "88",
    title: "Sample Video 88",
    thumbnail: "https://i.postimg.cc/6QtMd97B/Ei-Gy11-CSwix8ro-Qp-generated-image.jpg",
    description: "Description for video 88",
    views: 2400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 240,
  },
  {
    id: "89",
    title: "Sample Video 89",
    thumbnail: "https://i.postimg.cc/kX8Qgkj9/Jj-Rvz-Ssw-O3x6k7k-C-generated-image.jpg",
    description: "Description for video 89",
    views: 2500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 250,
  },
  {
    id: "90",
    title: "Sample Video 90",
    thumbnail: "https://i.postimg.cc/yxhxVjPy/n8-MP5-Njfoah-Mh-Sb2-generated-image.jpg",
    description: "Description for video 90",
    views: 2600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 260,
  },
  {
    id: "91",
    title: "Sample Video 91",
    thumbnail: "https://i.postimg.cc/SRmnQvjQ/x-FNVe-Cx77d-SOo-Toh-generated-image-1.jpg",
    description: "Description for video 91",
    views: 2700,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 270,
  },
  {
    id: "92",
    title: "Sample Video 92",
    thumbnail: "https://i.postimg.cc/bvGb4WSK/o-JMw-RU6yjg-Y9-Ib3b-generated-image.jpg",
    description: "Description for video 92",
    views: 2800,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 280,
  },
  {
    id: "93",
    title: "Sample Video 93",
    thumbnail: "https://i.postimg.cc/SNprCSYj/YL2-F71-Fo8c-Dt-C4l6-generated-image.jpg/",
    description: "Description for video 93",
    views: 2900,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 290,
  },
  {
    id: "94",
    title: "Sample Video 94",
    thumbnail: "https://i.postimg.cc/28VzdYpR/O5xc0-Vp-XVu-EX8-ZG8-generated-image.jpg",
    description: "Description for video 94",
    views: 3000,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 300,
  },
  {
    id: "95",
    title: "Sample Video 95",
    thumbnail: "https://i.postimg.cc/VLMPYB2p/Ri-QH469-RCKX5-Uws-V-generated-image.jpg",
    description: "Description for video 95",
    views: 3100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 310,
  },
  {
    id: "96",
    title: "Sample Video 96",
    thumbnail: "https://i.postimg.cc/HnXRm1sj/w-XIC7-Vt8q-Wi-GYL83-generated-image.jpg",
    description: "Description for video 96",
    views: 3200,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 320,
  },
  {
    id: "97",
    title: "Sample Video 97",
    thumbnail: "https://i.postimg.cc/Hk9yNgjS/bbx-Xb-Ns-Vd-UUwa-ECh-generated-image.jpg",
    description: "Description for video 97",
    views: 3300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 330,
  },
  {
    id: "98",
    title: "Sample Video 98",
    thumbnail: "https://i.postimg.cc/15xV5tqC/3z5-JEHi-G2-SQj-Xmn8-generated-image.jpg",
    description: "Description for video 98",
    views: 3400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 340,
  },
  {
    id: "99",
    title: "Sample Video 99",
    thumbnail: "https://i.postimg.cc/MTMXz2KJ/ml-DIL9-D4-KJ2o9-HYG-generated-image.jpg",
    description: "Description for video 99",
    views: 3500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 350,
  },
  {
    id: "100",
    title: "Sample Video 100",
    thumbnail: "https://i.postimg.cc/Y9W2J6bp/JR5n-Oe9lvyqs-Ygg-V-generated-image.jpg",
    description: "Description for video 100",
    views: 3600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 360,
  },
  {
    id: "101",
    title: "Sample Video 101",
    thumbnail: "https://i.postimg.cc/j21gS6SC/9t43b-UHb-JWQg-U9bb-generated-image.jpg",
    description: "Description for video 101",
    views: 4100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 410,
  },
  {
    id: "102",
    title: "Sample Video 102",
    thumbnail: "https://i.postimg.cc/CxgtBN4f/Wo8-CQf-X2-IOzoahxw-generated-image.jpg/",
    description: "Description for video 102",
    views: 4200,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 420,
  },
  {
    id: "103",
    title: "Sample Video 103",
    thumbnail: "https://i.postimg.cc/438F0TRz/c-L6-Iq-XWBzg-P3-QW53-generated-image.jpg",
    description: "Description for video 103",
    views: 4300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 430,
  },
  {
    id: "104",
    title: "Sample Video 104",
    thumbnail: "https://i.postimg.cc/3NGSW44B/KHpl8l-Mk-I9c-Eq63-Q-generated-image.jpg",
    description: "Description for video 104",
    views: 4400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 440,
  },
  {
    id: "105",
    title: "Sample Video 105",
    thumbnail: "https://i.postimg.cc/prdVHvmR/Sf-Bmfsr6guvn-TZpv-generated-image.jpg",
    description: "Description for video 105",
    views: 4500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 450,
  },
  {
    id: "106",
    title: "Sample Video 106",
    thumbnail: "https://i.postimg.cc/nh36ymvj/6r-Thity-Tf5d-KBYGx-generated-image.jpg",
    description: "Description for video 106",
    views: 4600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 460,
  },
  {
    id: "107",
    title: "Sample Video 107",
    thumbnail: "https://i.postimg.cc/9fvN2YzM/Apfd-Z1q-POq-Tlh-Efd-generated-image.jpg",
    description: "Description for video 107",
    views: 4700,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 470,
  },
  {
    id: "108",
    title: "Sample Video 108",
    thumbnail: "https://i.postimg.cc/YqqRJs8R/VYBecp-Ri-Qi-ZK2jn-L-generated-image.jpg",
    description: "Description for video 108",
    views: 4800,
    uploader: "",
    uploadDate: "1 day ago",
    likes: 480,
  },
  {
    id: "109",
    title: "Sample Video 109",
    thumbnail: "https://i.postimg.cc/PJfbnCbJ/3-Nr-CKns-Vx8-M5t-HIs-generated-image.jpg",
    description: "Description for video 109",
    views: 4900,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 490,
  },
  {
    id: "110",
    title: "Sample Video 110",
    thumbnail: "https://i.postimg.cc/DZ0c7DLr/Lsquz2-D7x-L8-Dm-Bfl-generated-image.jpg",
    description: "Description for video 110",
    views: 5000,
    uploader: "PREETAM SINGH",
    uploadDate: "1 day ago",
    likes: 500,
  },
  {
    id: "111",
    title: "Sample Video 111",
    thumbnail: "https://i.postimg.cc/Y2gd05TR/DALL-E-2025-03-20-09-46-22-A-professional-futuristic-You-Tube-thumbnail-for-a-coding-tutorial-titl.jpg",
    description: "Description for video 111",
    views: 5100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 510,
  },
  {
    id: "112",
    title: "Sample Video 112",
    thumbnail: "https://i.postimg.cc/TYtg3Q2Q/4291e875-8329-44e6-9a81-04e121ee8800.webp",
    description: "Description for video 112",
    views: 5200,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 520,
  },
  {
    id: "113",
    title: "Sample Video 113",
    thumbnail: "https://i.postimg.cc/hjMTQ0bS/o157wv8-Veds-V16-Ma-generated-image.jpg",
    description: "Description for video 113",
    views: 5300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 530,
  },
  {
    id: "114",
    title: "Sample Video 114",
    thumbnail: "https://i.postimg.cc/SRs86zDc/29e0cd3f-2d73-40c2-b146-ef832b66895d.webp",
    description: "Description for video 114",
    views: 5400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 540,
  },
  {
    id: "115",
    title: "Sample Video 115",
    thumbnail: "https://i.postimg.cc/NM0LSvmc/c759ec99-21bd-4c3b-91b1-94d486d71609.webp",
    description: "Description for video 115",
    views: 5500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 550,
  },
  {
    id: "116",
    title: "Sample Video 116",
    thumbnail: "https://i.postimg.cc/C5shxvjN/b29efcaf-a38e-4d0c-9b69-ba6bef5dff0d.webp",
    description: "Description for video 116",
    views: 5600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 560,
  },
  {
    id: "117",
    title: "Sample Video 117",
    thumbnail: "https://i.postimg.cc/YSYJ7vNN/1g-Xa-TROdq1-Kwr-G89-generated-image.jpg",
    description: "Description for video 117",
    views: 5700,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 570,
  },
  {
    id: "118",
    title: "Sample Video 118",
    thumbnail: "https://i.postimg.cc/JhV2p1ws/7-Snccv-HRT3xo-Bb-PI-generated-image.jpg",
    description: "Description for video 118",
    views: 5800,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 580,
  },
  {
    id: "119",
    title: "Sample Video 119",
    thumbnail: "https://i.postimg.cc/ot0ix26qig.js",
    description: "Description for video 119",
    views: 5900,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 590,
  },
  {
    id: "120",
    title: "Sample Video 120",
    thumbnail: "https://i.postimg.cc/MpjNKH2G/37h-IW08-Jkfv-JZ33-K-generated-image.jpg",
    description: "Description for video 120",
    views: 6000,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 600,
  },
  {
    id: "121",
    title: "Sample Video 121",
    thumbnail: "https://i.postimg.cc/7L8cC4wn/13t8g-X0vd-JNdm-QEQ-generated-image.jpg",
    description: "Description for video 121",
    views: 6100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 610,
  },
  {
    id: "1991",
    title: "Sample Video 1991",
    thumbnail: "https://i.postimg.cc/Bb6wWQB4/fynpc-O6q-YWe-Cq1-FT-generated-image.jpg",
    description: "Description for video 1991",
    views: 6100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 610,
  },
  {
    id: "153",
    title: "Sample Video 153",
    thumbnail: "https://i.postimg.cc/g0WSzKHM/zchf-QUf-GMq-U5g3s-E-generated-image.jpg",
    description: "Description for video 153",
    views: 9300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 930,
  },
  {
    id: "154",
    title: "Sample Video 154",
    thumbnail: "https://i.postimg.cc/GmhPqSzn/z-L0-Az2-Hpr-Yxs-Ynj-Z-generated-image.jpg",
    description: "Description for video 154",
    views: 9400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 940,
  },
  {
    id: "155",
    title: "Sample Video 155",
    thumbnail: "https://i.postimg.cc/FFVJ8VYr/o-Sj-Rme-Pk9-Mf1-DQGt-generated-image.jpg",
    description: "Description for video 155",
    views: 9500,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 950,
  },
  {
    id: "156",
    title: "Sample Video 156",
    thumbnail: "https://i.postimg.cc/RFsQr10b/s-Nj-IZCe-BNj4u-FEs4-generated-image.jpg",
    description: "Description for video 156",
    views: 9600,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 960,
  },
  {
    id: "157",
    title: "Sample Video 157",
    thumbnail: "https://i.postimg.cc/yxC9CfHj/C1-Fr-L660-Jqirn73j-generated-image.jpg",
    description: "Description for video 157",
    views: 9700,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 970,
  },
  {
    id: "158",
    title: "Sample Video 158",
    thumbnail: "https://i.postimg.cc/D0RNh3zD/Sc-ROOqzz2k-O1-Vx-Dk-generated-image.jpg",
    description: "Description for video 158",
    views: 9800,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 980,
  },
  {
    id: "159",
    title: "Sample Video 159",
    thumbnail: "https://i.postimg.cc/Yq4pcQRG/0-Kee2u-XSOA2n38p-N-generated-image.jpg",
    description: "Description for video 159",
    views: 9900,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 990,
  },
  {
    id: "160",
    title: "Sample Video 160",
    thumbnail: "https://i.postimg.cc/sgssMbyS/VVG7-Gc-X9dy-WKYGvc-generated-image.jpg",
    description: "Description for video 160",
    views: 10000,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 1000,
  },
  {
    id: "161",
    title: "Sample Video 161",
    thumbnail: "https://i.postimg.cc/9fbChb72/O5s6h-Idr7zz-Mg1l4-generated-image.jpg",
    description: "Description for video 161",
    views: 10100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 1010,
  },
  {
    id: "162",
    title: "Sample Video 162",
    thumbnail: "https://i.postimg.cc/g2PwsYFT/wq-Pp-YWxcg5-MHVRcn-generated-image.jpg",
    description: "Description for video 162",
    views: 10100,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 1010,
  },
  {
    id: "163",
    title: "Sample Video 163",
    thumbnail: "https://i.postimg.cc/CxQ1RDHk/Vsuz-Md-Btvpak-Ou-Wp-generated-image.jpg",
    description: "Description for video 163",
    views: 10300,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 1030,
  },
  {
    id: "164",
    title: "Sample Video 164",
    thumbnail: "https://i.postimg.cc/NFsYJfkQ/699xsn-MJJ4jw-DMn-I-generated-image.jpg",
    description: "Description for video 164",
    views: 10400,
    uploader: "Unknown",
    uploadDate: "1 day ago",
    likes: 1040,
  },
  {
    id: "165",
    title: "Sample Video 165",
    thumbnail: "https://i.postimg.cc/tTwRTH3b/Milt-FJs-Bxq-FMz-Kuf-generated-image.jpg",
    description: "Description for video 165",
    views: 10500,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1050,
  },
  {
    id: "166",
    title: "Sample Video 166",
    thumbnail: "https://i.postimg.cc/50vTBdcb/MJrp-Zz-Zc-AGcx-Vy64-generated-image.jpg",
    description: "Description for video 166",
    views: 10600,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1060,
  },
  {
    id: "167",
    title: "Sample Video 167",
    thumbnail: "https://i.postimg.cc/BQZ761vq/4-N19-Zog-Icw-DC0s-Rk-generated-image.jpg",
    description: "Description for video 167",
    views: 10700,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1070,
  },
  {
    id: "168",
    title: "Sample Video 168",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 168",
    views: 10800,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1080,
  },
  {
    id: "169",
    title: "Sample Video 169",
    thumbnail: "https://i.postimg.cc/hv85z9kr/Nhs-NSQm-RW2s-FITpr-generated-image.jpg",
    description: "Description for video 169",
    views: 10900,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1090,
  },
  {
    id: "170",
    title: "Sample Video 170",
    thumbnail: "https://i.postimg.cc/KYMScg89/Le-HY6-Jkq-B3iq-MFfn-generated-image.jpg",
    description: "Description for video 170",
    views: 11000,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1100,
  },
  {
    id: "171",
    title: "Sample Video 171",
    thumbnail: "https://i.postimg.cc/y6n5HTT1/Dm-Ar-Qf3doenib718-generated-image.jpg",
    description: "Description for video 171",
    views: 11100,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1110,
  },
  {
    id: "172",
    title: "Sample Video 172",
    thumbnail: "https://i.postimg.cc/VNyZRZzR/JBQOSHGFe7-Xuaa-Yt-generated-image.jpg",
    description: "Description for video 172",
    views: 11200,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1120,
  },
  {
    id: "173",
    title: "Sample Video 173",
    thumbnail: "https://i.postimg.cc/T32NH5by/4a-Ik-Kvee-S4-JZsp-MP-generated-image.jpg",
    description: "Description for video 173",
    views: 11300,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1130,
  },
  {
    id: "174",
    title: "Sample Video 174",
    thumbnail: "https://i.postimg.cc/Mp0VC9yt/hjssnjx81-Bv-Xut-Wy-generated-image.jpg",
    description: "Description for video 174",
    views: 11400,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1140,
  },
  {
    id: "175",
    title: "Sample Video 175",
    thumbnail: "https://i.postimg.cc/pdzC9thv/F8-SZbf9uy-Zee-Qs-Hs-generated-image.jpg",
    description: "Description for video 175",
    views: 11500,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1150,
  },
  {
    id: "176",
    title: "Sample Video 176",
    thumbnail: "https://i.postimg.cc/P59TM0XN/0-BT0pxgwm-K2r-IPw-N-generated-image.jpg",
    description: "Description for video 176",
    views: 11600,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1160,
  },
  {
    id: "177",
    title: "Sample Video 177",
    thumbnail: "https://i.postimg.cc/P59TM0XN/0-BT0pxgwm-K2r-IPw-N-generated-image.jpg",
    description: "Description for video 177",
    views: 11700,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1170,
  },
  {
    id: "178",
    title: "Sample Video 178",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 178",
    views: 11800,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1180,
  },
  {
    id: "179",
    title: "Sample Video 179",
    thumbnail: "https://i.postimg.cc/T1nFYy8X/n7-ORMb-W1g-F36-Y4-FH-generated-image.jpg",
    description: "Description for video 179",
    views: 11900,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1190,
  },
  {
    id: "180",
    title: "Sample Video 180",
    thumbnail: "https://i.postimg.cc/T1nFYy8X/n7-ORMb-W1g-F36-Y4-FH-generated-image.jpg",
    description: "Description for video 180",
    views: 12000,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1200,
  },
  {
    id: "181",
    title: "Sample Video 181",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 181",
    views: 12100,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1210,
  },
  {
    id: "182",
    title: "Sample Video 182",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 182",
    views: 12200,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1220,
  },
  {
    id: "183",
    title: "Sample Video 183",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 183",
    views: 12300,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1230,
  },
  {
    id: "184",
    title: "Sample Video 184",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 184",
    views: 12400,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1240,
  },
  {
    id: "185",
    title: "Sample Video 185",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 185",
    views: 12500,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1250,
  },
  {
    id: "186",
    title: "Sample Video 186",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 186",
    views: 12600,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1260,
  },
  {
    id: "187",
    title: "Sample Video 187",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 187",
    views: 12700,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1270,
  },
  {
    id: "188",
    title: "Sample Video 188",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 188",
    views: 12800,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1280,
  },
  {
    id: "189",
    title: "Sample Video 189",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 189",
    views: 12900,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1290,
  },
  {
    id: "190",
    title: "Sample Video 190",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 190",
    views: 13000,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1300,
  },
  {
    id: "191",
    title: "Sample Video 191",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 191",
    views: 13100,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1310,
  },
  {
    id: "193",
    title: "Sample Video 193",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 193",
    views: 13300,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1330,
  },
  {
    id: "194",
    title: "Sample Video 194",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 194",
    views: 13400,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1340,
  },
  {
    id: "195",
    title: "Sample Video 195",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 195",
    views: 13500,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1350,
  },
  {
    id: "196",
    title: "Sample Video 196",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 196",
    views: 13600,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1360,
  },
  {
    id: "197",
    title: "Sample Video 197",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 197",
    views: 13700,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1370,
  },
  {
    id: "198",
    title: "Sample Video 198",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 198",
    views: 13800,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1380,
  },
  {
    id: "199",
    title: "Sample Video 199",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 199",
    views: 13900,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1390,
  },
  {
    id: "200",
    title: "Sample Video 200",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 200",
    views: 14000,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1400,
  },
  {
    id: "201",
    title: "Sample Video 201",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 201",
    views: 14100,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1410,
  },
  {
    id: "202",
    title: "Sample Video 202",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 202",
    views: 14200,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1420,
  },
  {
    id: "203",
    title: "Sample Video 203",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 203",
    views: 14300,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1430,
  },
  {
    id: "204",
    title: "Sample Video 204",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 204",
    views: 14400,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1440,
  },
  {
    id: "205",
    title: "Sample Video 205",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 205",
    views: 14500,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1450,
  },
  {
    id: "206",
    title: "Sample Video 206",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 206",
    views: 14600,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1460,
  },
  {
    id: "207",
    title: "Sample Video 207",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 207",
    views: 14700,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1470,
  },
  {
    id: "208",
    title: "Sample Video 208",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 208",
    views: 14800,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1480,
  },
  {
    id: "209",
    title: "Sample Video 209",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 209",
    views: 14900,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1490,
  },
  {
    id: "210",
    title: "Sample Video 210",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 210",
    views: 15000,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1500,
  },
  {
    id: "211",
    title: "Sample Video 211",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 211",
    views: 15100,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1510,
  },
  {
    id: "212",
    title: "Sample Video 212",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 212",
    views: 15200,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1520,
  },
  {
    id: "213",
    title: "Sample Video 213",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 213",
    views: 15300,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1530,
  },
  {
    id: "214",
    title: "Sample Video 214",
    thumbnail: "https://i.postimg.cc/0jtNsJVt/o-M3wfz-Ljns3sjahd-generated-image.jpg",
    description: "Description for video 214",
    views: 15400,
    uploader: "Preetam Singh",
    uploadDate: "1 day ago",
    likes: 1540,
  }
]

